/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.javaeat1;

import java.awt.Color;
import java.util.List;

import javaeat.Productos;
import javaeat.Productos;
import javaeat.almacenClienteParticularEmpresa;
import javaeat.almacenProductos;
import javaeat.almacenRestaurantes;
import javaeat.Restaurante;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import poo.javaeat.Cliente;
import poo.javaeat.Empresa;
import poo.javaeat.Particular;
import poo.javaeat1.Pagina_Principal;
/**
 *
 * @author alexv
 */
public class ModificacionesRestaurante extends javax.swing.JFrame {
    
    almacenRestaurantes almRes = new almacenRestaurantes();
    private int fila;
    /**
     * Creates new form ProductosEnVenta
     */
    public ModificacionesRestaurante() {
        initComponents();
        this.fila = fila;

        almacenRestaurantes almRes = new almacenRestaurantes();
        
        almacenProductos comidas = new almacenProductos();

        DefaultTableModel modeloDefault = new DefaultTableModel();
        String[] cabecera = new String[]{"CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"};
        modeloDefault.setColumnIdentifiers(cabecera);

        jTable1.setModel(modeloDefault);

        TableModel modeloDatos = jTable1.getModel();

        Object rowData[] = new Object[8];
        
        for (Restaurante r : almRes.getRestaurante()) {
            rowData[0] = r.getCif();
            rowData[1] = r.getNombre();
            rowData[2] = r.getDireccion();
            rowData[3] = r.getEspecialidad();
            rowData[4] = r.getCalificacion();
            rowData[5] = r.getGastosEnvio();
            rowData[6] = r.getTiempoMedioEnvio();
            rowData[7] = r.isCateringParaEmpresas();
            
            
            modeloDefault.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nuevoProducto = new java.awt.Label();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        subirProducto = new javax.swing.JButton();
        direccion = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        cif = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        modificarComida = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        especialidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        calificacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gastosdeenvio = new javax.swing.JTextField();
        tiempodeenvio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cateringparaempresas = new javax.swing.JCheckBox();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nuevoProducto.setAlignment(java.awt.Label.CENTER);
        nuevoProducto.setBackground(new java.awt.Color(51, 51, 255));
        nuevoProducto.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        nuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        nuevoProducto.setText("AÑADIR / ELIMINAR NUEVOS RESTAURANTES");
        jPanel1.add(nuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 740, 94));

        back.setBackground(new java.awt.Color(51, 51, 255));
        back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back.setText("ATRÁS");
        back.setBorder(null);
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subirProducto.setBackground(new java.awt.Color(51, 51, 255));
        subirProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subirProducto.setForeground(new java.awt.Color(255, 255, 255));
        subirProducto.setText("SUBIR RESTAURANTE");
        subirProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirProductoActionPerformed(evt);
            }
        });
        jPanel2.add(subirProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 410, 60));

        direccion.setBackground(new java.awt.Color(204, 204, 204));
        direccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionActionPerformed(evt);
            }
        });
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 240, 20));

        nombre.setBackground(new java.awt.Color(204, 204, 204));
        nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        jPanel2.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 240, 30));

        cif.setBackground(new java.awt.Color(204, 204, 204));
        cif.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifActionPerformed(evt);
            }
        });
        jPanel2.add(cif, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 240, 30));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 480, 250));

        modificarComida.setBackground(new java.awt.Color(51, 102, 255));
        modificarComida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        modificarComida.setForeground(new java.awt.Color(255, 255, 255));
        modificarComida.setText("MODIFICAR RESTAURANTE");
        modificarComida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        modificarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarComidaActionPerformed(evt);
            }
        });
        jPanel2.add(modificarComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 240, 60));

        eliminar.setBackground(new java.awt.Color(51, 102, 255));
        eliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setText("BORRAR");
        eliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        jPanel2.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 220, 60));

        jLabel1.setText("Cif:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, -1));

        jLabel2.setText("Nombre:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, -1));

        jLabel3.setText("Direccion:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, -1));

        jLabel4.setText("Especialidad:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        especialidad.setBackground(new java.awt.Color(204, 204, 204));
        especialidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        especialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadActionPerformed(evt);
            }
        });
        jPanel2.add(especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, -1));

        jLabel5.setText("Calificacion:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, -1));

        calificacion.setBackground(new java.awt.Color(204, 204, 204));
        calificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calificacionActionPerformed(evt);
            }
        });
        jPanel2.add(calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 180, -1));

        jLabel6.setText("Gastos de Envio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 140, -1));

        gastosdeenvio.setBackground(new java.awt.Color(204, 204, 204));
        gastosdeenvio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gastosdeenvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastosdeenvioActionPerformed(evt);
            }
        });
        jPanel2.add(gastosdeenvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, -1));

        tiempodeenvio.setBackground(new java.awt.Color(204, 204, 204));
        tiempodeenvio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tiempodeenvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempodeenvioActionPerformed(evt);
            }
        });
        jPanel2.add(tiempodeenvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 180, -1));

        jLabel7.setText("Tiempo de Envio:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 100, -1));

        cateringparaempresas.setText("Catering");
        jPanel2.add(cateringparaempresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 810, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionActionPerformed
        // TODO add your handling code here:
        String txt = direccion.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el precio", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_direccionActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
        String txt = nombre.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca las caracteristicas", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_nombreActionPerformed

    private void cifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifActionPerformed
        // TODO add your handling code here:
        String txt = cif.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "Inserte el titulo del producto", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_cifActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Admin abrir = new Admin();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void subirProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirProductoActionPerformed
        almacenRestaurantes almRes = new almacenRestaurantes();
       
        almRes.getRestaurante().add(new Restaurante(cif.getText(), nombre.getText(), 
                direccion.getText(), especialidad.getText(), Double.parseDouble(calificacion.getText()), 
                Double.parseDouble(gastosdeenvio.getText()),Integer.parseInt(tiempodeenvio.getText()),cateringparaempresas.isSelected()));
        almRes.EscribirFichero("src/main/java/data");
    }//GEN-LAST:event_subirProductoActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         fila = jTable1.getSelectedRow();
    }//GEN-LAST:event_jTable1MouseClicked

    private void modificarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarComidaActionPerformed
         
    }//GEN-LAST:event_modificarComidaActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
      almacenRestaurantes almRes = new almacenRestaurantes();
DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
int selectedRow = jTable1.getSelectedRow();
if (selectedRow != -1) { // Verificar si hay una fila seleccionada
    dtm.removeRow(selectedRow);
    almRes.borrarDatos();
    // Volver a escribir los restaurantes restantes en el fichero
    for (int i = 0; i < dtm.getRowCount(); i++) {
        String cif = dtm.getValueAt(i, 0).toString();
        String nombre = dtm.getValueAt(i, 1).toString();
        String direccion = dtm.getValueAt(i, 2).toString();
        String especialidad = dtm.getValueAt(i, 3).toString();
        double calificacion = Double.parseDouble(dtm.getValueAt(i, 4).toString());
        double gastosEnvio = Double.parseDouble(dtm.getValueAt(i, 5).toString());
        int tiempoMedioEnvio = Integer.parseInt(dtm.getValueAt(i, 6).toString());
        boolean cateringParaEmpresas = Boolean.parseBoolean(dtm.getValueAt(i, 7).toString());
        // Crear el objeto Restaurante y agregarlo al almacenRestaurantes
        almRes.getRestaurante().add(new Restaurante(cif, nombre, direccion, especialidad, calificacion,
                gastosEnvio, tiempoMedioEnvio, cateringParaEmpresas));
    }
    almRes.EscribirFichero("src/main/java/data");
}

    }//GEN-LAST:event_eliminarActionPerformed

    private void especialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadActionPerformed
         String txt = especialidad.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this,"Inserte el titulo del producto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_especialidadActionPerformed

    private void calificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calificacionActionPerformed
         String txt = calificacion.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this,"Inserte el titulo del producto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_calificacionActionPerformed

    private void gastosdeenvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastosdeenvioActionPerformed
         String txt = gastosdeenvio.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this,"Inserte el titulo del producto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_gastosdeenvioActionPerformed

    private void tiempodeenvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempodeenvioActionPerformed
         String txt = tiempodeenvio.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this,"Inserte el titulo del producto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_tiempodeenvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField calificacion;
    private javax.swing.JCheckBox cateringparaempresas;
    private javax.swing.JTextField cif;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField especialidad;
    private javax.swing.JTextField gastosdeenvio;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarComida;
    private javax.swing.JTextField nombre;
    private java.awt.Label nuevoProducto;
    private javax.swing.JButton subirProducto;
    private javax.swing.JTextField tiempodeenvio;
    // End of variables declaration//GEN-END:variables
}
