/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.javaeat1;

import java.awt.Color;
import java.net.URL;
import javaeat.almacenContra;
import javaeat.almacenNombreUsuarios;
import javaeat.almacenClienteParticularEmpresa;
import javaeat.almacenProductos;
import javaeat.Restaurante;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poo.javaeat.Cliente;
/**
 *
 * @author alexv
 */
public class Pagina_Principal extends javax.swing.JFrame {

    private ImageIcon icon;
    almacenClienteParticularEmpresa almacenParti;
    Restaurante restaurante;
    
    public Pagina_Principal() {
        initComponents();
        
        
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        javaComp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        iniciarSesion = new java.awt.Label();
        ponerCorreo = new java.awt.TextField();
        correo = new java.awt.Label();
        contraseña = new java.awt.Label();
        ponerContraseña = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        registrarse = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        registrarseParticular = new javax.swing.JButton();
        texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javaComp.setBackground(new java.awt.Color(51, 51, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JavaEat");

        javax.swing.GroupLayout javaCompLayout = new javax.swing.GroupLayout(javaComp);
        javaComp.setLayout(javaCompLayout);
        javaCompLayout.setHorizontalGroup(
            javaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, javaCompLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(531, 531, 531))
        );
        javaCompLayout.setVerticalGroup(
            javaCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, javaCompLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(javaComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 140));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciarSesion.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        iniciarSesion.setText("INICIO DE SESIÓN");
        jPanel3.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 290, 60));

        ponerCorreo.setBackground(new java.awt.Color(204, 204, 204));
        ponerCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ponerCorreo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ponerCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerCorreoActionPerformed(evt);
            }
        });
        jPanel3.add(ponerCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 450, -1));

        correo.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        correo.setText("Introduce tu correo");
        jPanel3.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, -1));

        contraseña.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        contraseña.setText("Introduce la contraseña");
        jPanel3.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 170, -1));

        ponerContraseña.setBackground(new java.awt.Color(204, 204, 204));
        ponerContraseña.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ponerContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ponerContraseñaActionPerformed(evt);
            }
        });
        jPanel3.add(ponerContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 450, -1));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        registrarse.setBackground(new java.awt.Color(204, 255, 255));
        registrarse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrarse.setText("REGISTRARSE COMO EMPRESA");
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseMouseExited(evt);
            }
        });
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });

        aceptar.setBackground(new java.awt.Color(204, 255, 255));
        aceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aceptarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aceptarMouseExited(evt);
            }
        });
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        registrarseParticular.setBackground(new java.awt.Color(204, 255, 255));
        registrarseParticular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrarseParticular.setText("RESGISTRARSE COMO PARTICULAR");
        registrarseParticular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarseParticularMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarseParticularMouseExited(evt);
            }
        });
        registrarseParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseParticularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(registrarseParticular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarseParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 820, 110));

        texto.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 0, 0));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 560, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 820, 370));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   JavaEat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 120));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseParticularActionPerformed
        registrarseParticular abrir = new registrarseParticular();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarseParticularActionPerformed

    private void registrarseParticularMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseParticularMouseExited
        registrarseParticular.setForeground(Color.white);
    }//GEN-LAST:event_registrarseParticularMouseExited

    private void registrarseParticularMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseParticularMouseEntered
        registrarseParticular.setForeground(Color.black);
    }//GEN-LAST:event_registrarseParticularMouseEntered

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        if (ponerCorreo.getText().equals("admin@javaeat.com") && (ponerContraseña.getText().equals("admin"))) {
            Admin a = new Admin();
            a.setVisible(true);
            this.setVisible(false);

        }
        almacenClienteParticularEmpresa alm = new almacenClienteParticularEmpresa();
        for (Cliente cliente : alm.getListaClientes()) {

            if (cliente.getCorreo().equals(ponerCorreo.getText()) && cliente.getContraseña().equals(ponerContraseña.getText())) {
                seleccion_restaurante a = new seleccion_restaurante(cliente) ;
                a.setVisible(true);
                this.setVisible(false);

                break;
            }else{
                texto.setText("Datoss introducidos incorrectos.");

            }

        }

    }//GEN-LAST:event_aceptarActionPerformed

    private void aceptarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseExited
        aceptar.setForeground(Color.white);
    }//GEN-LAST:event_aceptarMouseExited

    private void aceptarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseEntered
        aceptar.setForeground(Color.black);
    }//GEN-LAST:event_aceptarMouseEntered

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        registrarseEmpresa abrir = new registrarseEmpresa();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarseActionPerformed

    private void registrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseExited
        registrarse.setForeground(Color.white); //cuando sacamos el raton se vuelve a poner negro
    }//GEN-LAST:event_registrarseMouseExited

    private void registrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseEntered
        registrarse.setForeground(Color.black);//cuando pasamos el raton por el botón se cambia la letra a negra
    }//GEN-LAST:event_registrarseMouseEntered

    private void ponerContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerContraseñaActionPerformed
        String txt = ponerCorreo.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "Introduce tu contraseña", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_ponerContraseñaActionPerformed

    private void ponerCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ponerCorreoActionPerformed
        String txt = ponerCorreo.getText();
        if (txt.equals("")) {
            JOptionPane.showMessageDialog(this, "Introduce tu correo", "Mensaje", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_ponerCorreoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagina_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagina_Principal().setVisible(true);
                //new ImageIcon("source/logo.jpg");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private java.awt.Label contraseña;
    private java.awt.Label correo;
    private java.awt.Label iniciarSesion;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel javaComp;
    private javax.swing.JPasswordField ponerContraseña;
    private java.awt.TextField ponerCorreo;
    private javax.swing.JButton registrarse;
    private javax.swing.JButton registrarseParticular;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
}
