/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.javaeat1;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import javaeat.OrdenarCatering;
import javaeat.OrdenarRelevancia;
import javaeat.OrdenarTiempoEnvio;
import javaeat.Productos;
import javaeat.Prueba;
import javaeat.almacenProductos;
import javaeat.almacenRestaurantes;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import poo.javaeat.Cliente;
import javaeat.Restaurante;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author alexv
 */
public class seleccion_restaurante extends javax.swing.JFrame {

    Cliente cliente;
    Restaurante restaurante;
    
    private int posProsel;
    private ArrayList<Productos> prodSel;
    private ArrayList<Productos> productosFiltrados;
    private TableRowSorter trsfiltro;
    
    
    /**
     * Creates new form seleccion_restaurante
     */
    public seleccion_restaurante(Cliente cliente) {
        initComponents();
        this.cliente=cliente;
        this.restaurante=restaurante;
        llenarTabla();
        this.prodSel = new ArrayList<Productos>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRestaurantes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jtiempoENVIO = new javax.swing.JButton();
        ordenarcateringBOTOB = new javax.swing.JButton();
        relevanciaBOTON = new javax.swing.JButton();
        busqueda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cerrrarBOTON = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tablaRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        }
    );
    jScrollPane1.setViewportView(tablaRestaurantes);

    jButton1.setBackground(new java.awt.Color(204, 255, 255));
    jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jButton1.setText("HACER UN PEDIDO");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jtiempoENVIO.setBackground(new java.awt.Color(204, 255, 255));
    jtiempoENVIO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jtiempoENVIO.setText("ORDENAR POR TIEMPO ENVIO");
    jtiempoENVIO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jtiempoENVIO.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jtiempoENVIOActionPerformed(evt);
        }
    });

    ordenarcateringBOTOB.setBackground(new java.awt.Color(204, 255, 255));
    ordenarcateringBOTOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    ordenarcateringBOTOB.setText("ORDENAR POR CATERING");
    ordenarcateringBOTOB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    ordenarcateringBOTOB.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ordenarcateringBOTOBActionPerformed(evt);
        }
    });

    relevanciaBOTON.setBackground(new java.awt.Color(204, 255, 255));
    relevanciaBOTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    relevanciaBOTON.setText("ORDENAR POR RELEVANCIA");
    relevanciaBOTON.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    relevanciaBOTON.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            relevanciaBOTONActionPerformed(evt);
        }
    });

    busqueda.setBackground(new java.awt.Color(204, 255, 255));
    busqueda.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            busquedaActionPerformed(evt);
        }
    });
    busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            busquedaKeyTyped(evt);
        }
    });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    jLabel1.setText("Ordenar por codigo postal:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(47, 47, 47)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtiempoENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(55, 55, 55)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ordenarcateringBOTOB, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(relevanciaBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(49, 49, 49))))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(32, 32, 32)
            .addComponent(jLabel1)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ordenarcateringBOTOB, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtiempoENVIO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(relevanciaBOTON, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(60, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(51, 51, 255));

    jLabel2.setBackground(new java.awt.Color(51, 51, 255));
    jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
    jLabel2.setText("RESTAURANTES");

    cerrrarBOTON.setBackground(new java.awt.Color(51, 102, 255));
    cerrrarBOTON.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    cerrrarBOTON.setText("ATRÁS");
    cerrrarBOTON.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cerrrarBOTONActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(241, 241, 241))
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(cerrrarBOTON)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addComponent(cerrrarBOTON)
            .addGap(4, 4, 4)
            .addComponent(jLabel2)
            .addContainerGap(39, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pedidos r1 = new Pedidos(cliente);
        r1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtiempoENVIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtiempoENVIOActionPerformed
        
        almacenRestaurantes almRes = new almacenRestaurantes();
        Collections.sort(almRes.getRestaurante(), new OrdenarTiempoEnvio());
        DefaultTableModel modeloDefault = new DefaultTableModel();
        String[] cabecera = new String[]{"CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"};
        modeloDefault.setColumnIdentifiers(cabecera);

        tablaRestaurantes.setModel(modeloDefault);

        TableModel modeloDatos = tablaRestaurantes.getModel();

        Object rowData[] = new Object[8];

        for (int i = 0; i < almRes.getRestaurante().size(); i++) {
            rowData[0] = almRes.getRestaurante().get(i).getCif();
            rowData[1] = almRes.getRestaurante().get(i).getNombre();
            rowData[2] = almRes.getRestaurante().get(i).getDireccion();
            rowData[3] = almRes.getRestaurante().get(i).getEspecialidad();
            rowData[4] = almRes.getRestaurante().get(i).getCalificacion();
            rowData[5] = almRes.getRestaurante().get(i).getGastosEnvio();
            rowData[6] = almRes.getRestaurante().get(i).getTiempoMedioEnvio();
            rowData[7] = almRes.getRestaurante().get(i).isCateringParaEmpresas();
            modeloDefault.addRow(rowData);
        }        
    }//GEN-LAST:event_jtiempoENVIOActionPerformed

    private void ordenarcateringBOTOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarcateringBOTOBActionPerformed
        
        almacenRestaurantes almRes = new almacenRestaurantes();
        almacenProductos almProd = new almacenProductos();
        
        Collections.sort(almRes.getRestaurante(), new OrdenarCatering());
        DefaultTableModel modeloDefault = new DefaultTableModel();
        String[] cabecera = new String[]{"CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"};
        modeloDefault.setColumnIdentifiers(cabecera);

        tablaRestaurantes.setModel(modeloDefault);

        TableModel modeloDatos = tablaRestaurantes.getModel();

        Object rowData[] = new Object[9];

        for (int i = 0; i < almRes.getRestaurante().size(); i++) {
            rowData[0] = almRes.getRestaurante().get(i).getCif();
            rowData[1] = almRes.getRestaurante().get(i).getNombre();
            rowData[2] = almRes.getRestaurante().get(i).getDireccion();
            rowData[3] = almRes.getRestaurante().get(i).getEspecialidad();
            rowData[4] = almRes.getRestaurante().get(i).getCalificacion();
            rowData[5] = almRes.getRestaurante().get(i).getGastosEnvio();
            rowData[6] = almRes.getRestaurante().get(i).getTiempoMedioEnvio();
            rowData[7] = almRes.getRestaurante().get(i).isCateringParaEmpresas();
            rowData[8] = almProd.getProducto().get(i).getTITULO();
            
            modeloDefault.addRow(rowData);
        }        
    }//GEN-LAST:event_ordenarcateringBOTOBActionPerformed

    private void relevanciaBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relevanciaBOTONActionPerformed
        
        almacenRestaurantes almRes = new almacenRestaurantes();
        almacenProductos almProd = new almacenProductos();
        
        Collections.sort(almRes.getRestaurante(), new OrdenarRelevancia());
        DefaultTableModel modeloDefault = new DefaultTableModel();
        String[] cabecera = new String[]{"CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"};
        modeloDefault.setColumnIdentifiers(cabecera);

        tablaRestaurantes.setModel(modeloDefault);

        TableModel modeloDatos = tablaRestaurantes.getModel();

        Object rowData[] = new Object[9];

        for (int i = 0; i < almRes.getRestaurante().size(); i++) {
            rowData[0] = almRes.getRestaurante().get(i).getCif();
            rowData[1] = almRes.getRestaurante().get(i).getNombre();
            rowData[2] = almRes.getRestaurante().get(i).getDireccion();
            rowData[3] = almRes.getRestaurante().get(i).getEspecialidad();
            rowData[4] = almRes.getRestaurante().get(i).getCalificacion();
            rowData[5] = almRes.getRestaurante().get(i).getGastosEnvio();
            rowData[6] = almRes.getRestaurante().get(i).getTiempoMedioEnvio();
            rowData[7] = almRes.getRestaurante().get(i).isCateringParaEmpresas();
            rowData[8] = almProd.getProducto().get(i).getTITULO();
            modeloDefault.addRow(rowData);
        }
    }//GEN-LAST:event_relevanciaBOTONActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busquedaActionPerformed

    private void busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyTyped
        busqueda.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (busqueda.getText());
                busqueda.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(tablaRestaurantes.getModel());
        tablaRestaurantes.setRowSorter(trsfiltro);
    }//GEN-LAST:event_busquedaKeyTyped

    private void cerrrarBOTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrrarBOTONActionPerformed
        Pagina_Principal p_p = new Pagina_Principal();
        p_p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cerrrarBOTONActionPerformed

    private void llenarTabla() {
        almacenRestaurantes almRes = new almacenRestaurantes();

        DefaultTableModel modeloDefault = new DefaultTableModel();
        String[] cabecera = new String[]{"CIF", "Nombre", "Direccion", "Especialidad", "Calificacion", "gastosEnvio", "tiempomedioEnvio", "Catering"};
        modeloDefault.setColumnIdentifiers(cabecera);

        tablaRestaurantes.setModel(modeloDefault);

        TableModel modeloDatos = tablaRestaurantes.getModel();

        Object rowData[] = new Object[8];
        
        for (Restaurante r : almRes.getRestaurante()) {
            rowData[0] = r.getCif();
            rowData[1] = r.getNombre();
            rowData[2] = r.getDireccion();
            rowData[3] = r.getEspecialidad();
            rowData[4] = r.getCalificacion();
            rowData[5] = r.getGastosEnvio();
            rowData[6] = r.getTiempoMedioEnvio();
            rowData[7] = r.isCateringParaEmpresas();
                      
            modeloDefault.addRow(rowData);
        }
        
        

    }
    
    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(busqueda.getText() ,2));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busqueda;
    private javax.swing.JButton cerrrarBOTON;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jtiempoENVIO;
    private javax.swing.JButton ordenarcateringBOTOB;
    private javax.swing.JButton relevanciaBOTON;
    private javax.swing.JTable tablaRestaurantes;
    // End of variables declaration//GEN-END:variables
}
